version: '3.8'
services:
    api:
        build: ./api
        container_name: api_backend
        ports:
            - '4000:4000'
        volumes:
            - ./api:/app
            - ./api/node_modules:/app/node_modules
        networks:
            - react-nginx

#    3dview:
#        build: ./3dview
#        container_name: 3dview_frontend
#        ports:
#            - '3001:3000'
#        volumes:
#            - ./3dview:/app
#            - ./3dview/node_modules:/app/node_modules
#        stdin_open: true
#        tty: true
#        networks:
#            - react-nginx

    models-view:
        build: ./models-view
        container_name: models-view
        ports:
            - "8081:8081"
            - "19000:19000"
            - "19001:19001"
        environment:
            #- "./frontend/.env"
            - CHOKIDAR_USEPOLLING=true  # Required for hot reloading to work in Windows
        volumes:
            - ./models-view:/app
            - ./models-view/node_modules:/app/node_modules  # Prevents node_modules from being overriten
        tty: true
        networks:
            - react-nginx

networks:
    react-nginx:
        driver: bridge