version: '3.8'
services:
    api:
        build: ./api
        container_name: api_backend
        ports:
            - '4000:4000'
        volumes:
            - ./api:/app
            - ./api/node_modules:/app/node_modules



#    3dview:
#        build: ./3dview
#        container_name: 3dview_frontend
#        ports:
#            - '3001:3000'
#        volumes:
#            - ./3dview:/app
#            - ./3dview/node_modules:/app/node_modules
#        stdin_open: true
#        tty: true
#        networks:
#            - react-nginx

    models-view:
        image: moviendome/react-native-example:latest
        tty: true
        stdin_open: true
        user: root
        volumes:
            - ./models-view:/app
            - ./models-view/node_modules:/app/node_modules
        environment:
            - NODE_ENV= development
            - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_ADDRESS}
        ports:
            - '3000:3000'
            - '19000:19000'
            - '19001:19001'
            - '19002:19002'
            - '19006:19006'
        command: >
            /bin/bash -c "yarn install && expo start${PLATFORM}"
        networks:
            - react-nginx

networks:
    react-nginx:
        driver: bridge