version: '3.8'
services:
    api:
        build: ./api
        container_name: api_backend
        ports:
            - '4000:4000'
        volumes:
            - ./api:/app
            - ./api/node_modules:/app/node_modules
        networks:
            - react-nginx

#    3dview:
#        build: ./3dview
#        container_name: 3dview_frontend
#        ports:
#            - '3001:3000'
#        volumes:
#            - ./3dview:/app
#            - ./3dview/node_modules:/app/node_modules
#        stdin_open: true
#        tty: true
#        networks:
#            - react-nginx


    models-view:
        container_name: models-view
        build: ./models-view/
        ports:
            - '19000:19000'
            - '19001:19001'
            - '19002:19002'
        volumes:
            - ./models-view/:/app
            - ./models-view/node_modules:/app/node_modules
        env_file: .env
        networks:
            - react-nginx

networks:
    react-nginx:
        driver: bridge